import type { Metadata } from "next";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pass",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light">
      <QueryClientProvider client={queryClient}>
        <body>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
